name               = "voxlabs"
main               = "src/worker.js"
compatibility_date = "2026-07-05"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[assets]
directory = "./dist"
binding   = "ASSETS"

[[services]]
binding = "TTS_API"
service = "text-to-speech"

[[services]]
binding = "VISITORS_API"
service = "visitors"

[[kv_namespaces]]
binding = "USAGE_KV"
id = "5e310d2ae4394fa690fc47bd980f57a7"

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADxGWHctWk2yfROX"